image: node:lts

stages:
  - setup

  - test

  - build/deploy

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s

cache:
  - key:
      files:
        - package-lock.json

    paths:
      - node_modules/

install:
  stage: setup

  script:
    - npm install

  artifacts:
    paths:
      - node_modules/

prettier/lint/jest:
  stage: test

  script:
    - npm run prettier
    - npm run lint
    - npm run test

  allow_failure: false

build/deploy:
  stage: build/deploy

  script: 
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'